services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-chat-backend
    #ports:
    #  - "8000:8000"
    environment:
      # Путь к модели (можно изменить через .env файл)
      - MODEL_PATH=${MODEL_PATH:-/app/models/ggml-old-vic13b-q4_0.bin}
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
      - SESSION_TIMEOUT=${SESSION_TIMEOUT:-3600}
      - CLEANUP_INTERVAL=${CLEANUP_INTERVAL:-300}
    volumes:
      # Монтируем директорию с моделями
      - ${MODEL_HOST_PATH:-/home/luksa/git/AI_Workshop/ai-goat/tasks/models}:/app/models:ro
    networks:
      - ai-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: '4.0'
        reservations:
          memory: 8G
          cpus: '2.0'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-chat-frontend
    ports:
      - "50011:5000"
    environment:
      - FRONTEND_HOST=0.0.0.0
      - FRONTEND_PORT=5000
      - BACKEND_URL=http://backend:8000
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT:-300}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ai-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  ai-chat-network:
    driver: bridge
    name: ai-chat-network

# Пример .env файла (создайте его в директории compose/)
# MODEL_PATH=/app/models/ggml-old-vic13b-q4_0.bin
# MODEL_HOST_PATH=/home/luksa/git/AI_Workshop/ai-goat/tasks/models
# REQUEST_TIMEOUT=300
# SESSION_TIMEOUT=3600
# CLEANUP_INTERVAL=300
